boxshop/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include('shop.urls')),
    re_path(r'^cart/', include('cart.urls')),
] 

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf.urls import url
from . import views
from django.urls import include, path, re_path

app_name = 'cart'

urlpatterns = [
    re_path(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
    re_path(r'^$', views.CartDetail, name='CartDetail'),
]

shop/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from shop.views import base_view, product_view, category_view
from . import views

app_name = 'shop'

urlpatterns = [
    re_path(r'^$', base_view, name='base'),
    re_path(r'^product/(?P<product_slug>[-\w]+)/$', product_view, name='product_detail'),
    re_path(r'^category/(?P<category_slug>[-\w]+)/$', category_view, name='category_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

shop/models.py
from __future__ import unicode_literals
from django.urls import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from transliterate import translit


class Category(models.Model):
	name = models.CharField(max_length=100)
	slug = models.SlugField(blank=True)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('category_detail', kwargs={'category_slug': self.slug})

def pre_save_category_slug(sender, instance, *args, **kwargs):
	if not instance.slug:
		slug = slugify(translit(str(instance.name), reversed=True))
		instance.slug = slug

pre_save.connect(pre_save_category_slug, sender=Category)

class Brand(models.Model):
	name = models.CharField(max_length=100)

	def __str__(self):
		return self.name

def image_folder(instance, filename):
	filename = instance.slug + '.' + filename.split('.')[1]
	return "{0}/{1}".format(instance.slug, filename)


class ProductManager(models.Manager):

	def all(self, *args, **kwargs):
		return super(ProductManager, self).get_queryset().filter(available=True)


class Product(models.Model):
	category = models.ForeignKey(Category, on_delete=models.CASCADE)
	brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
	title = models.CharField(max_length=130)
	slug = models.SlugField(blank=True)
	description = models.TextField()
	image = models.ImageField(upload_to=image_folder)
	price = models.DecimalField(max_digits=9, decimal_places=2)
	available = models.BooleanField(default=True)
	objects = ProductManager()

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('product_detail', kwargs={'product_slug': self.slug})

def pre_save_product_slug(sender, instance, *args, **kwargs):
	if not instance.slug:
		slug = slugify(str(instance.title), reversed=True)
		instance.slug = slug

pre_save.connect(pre_save_product_slug, sender=Product)

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 10)]
class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def CartAdd(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'],
                                  update_quantity=cd['update'])
    return redirect('cart:CartDetail')


def CartRemove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:CartDetail')


def CartDetail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

shop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from cart.forms import CartAddProductForm
from shop.models import Category, Product



def base_view(request):
	categories = Category.objects.all()
	products = Product.objects.all()
	context = {
		'categories': categories,
		'products': products
	}
	return render(request, 'base.html', context)


def product_view(request, product_slug):
	product = Product.objects.get(slug=product_slug)
	cart_product_form = CartAddProductForm()
	context = {
		'product': product,
		'cart_product_form': cart_product_form
	}
	return render(request, 'product.html', context)


def category_view(request, category_slug):
	category = Category.objects.get(slug=category_slug)
	context = {
		'category': category
	}
	return render(request, 'category.html', context)

cart/templates/cart/detail.html
{% extends "base.html" %}
{% block title %}
  Ваша корзина товаров
{% endblock %}
{% block content %}
  <h1>Ваша корзина товаров</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>Изображение</th>
        <th>Продукт</th>
        <th>Количество</th>
        <th>Удалить</th>
        <th>Полная цена</th>
        <th>Цена</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{{ product.image.url }}" alt="" />
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>{{ item.quantity }}</td>
            <td><a href="{% url "cart:CartRemove" product.id %}">Удалить</a></td>
            <td class="num">{{ item.price }} руб.</td>
            <td class="num">{{ item.total_price }} руб.</td>
          </tr>
        {% endwith %}
      {% endfor %}
        <tr class="total">
          <td>Total</td>
          <td colspan="4"></td>
          <td class="num">{{ cart.get_total_price }} руб.</td>
        </tr>
    </tbody>
  </table>
  <p class="text-right">
    <a href="{% url 'shop:ProductList"%}" class="btn">Продолжить Шопинг</a>
    <a href="#">Оформить заказ</a>
  </p>
{% endblock %}

shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>BoxShop - Домашня сторінка</title>

    <!-- Bootstrap Core CSS -->
    <link href='{% static "css/bootstrap.min.css" %}' rel="stylesheet">

    <!-- Custom CSS -->
    <link href='{% static "css/shop-homepage.css" %}' rel="stylesheet">




</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Інтернет магазин автоаксесуарів</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#">Про нас</a>
                    </li>
                    <li>
                        <a href="#">Послуги</a>
                    </li>
                    <li>
                        <a href="#">Контакти</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">
        {% block title %}
            {% if category %} {{ category.name }} {% else %} Сторінка товарів {% endif %}
        {% endblock %}
    	{% block content %}
        <div class="row">

            <div class="col-md-3">
                <p class="lead">BoxShop.ua</p>
                <div class="list-group">
                	{% for category in categories %}
                        {% if category.slug == category.slug %}{% endif %}
                            <a href="{{ Category.get_absolute_url }}" class="list-group-item">{{ category.name }}</a>
                	{% endfor %}
                </div>
            </div>

            <div class="col-md-9">

                <div class="row carousel-holder">

                    <div class="col-md-12">
                        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                            </ol>
                            <div class="carousel-inner">
                                <div class="item active">
                                    <img class="slide-image" src="https://gearinstitute.com/wp-content/uploads/2017/09/bike_racks-800x300.jpg" alt="">
                                </div>
                                <div class="item">
                                    <img class="slide-image" src="https://gearinstitute.com/wp-content/uploads/roof_mounted_bike_racks-00-800x300.jpg" alt="">
                                </div>
                                <div class="item">
                                    <img class="slide-image" src="https://gearinstitute.com/wp-content/uploads/5Kuat-Bike-Rack-800x300.jpg" alt="">
                                </div>
                            </div>
                            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left"></span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right"></span>
                            </a>
                        </div>
                    </div>

                </div>
                <br>
                <div class="row">
                	{% for product in products %}
                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <div class="thumbnail">
                            <img src='{{ product.image.url }}' alt="" style="width: 100%; height: 250px">
                            <div class="caption">
                                <h4 class="pull-right">{{ product.price }} грн.</h4>
                                <h5><strong><a href="{{ Product.get_absolute_url }}">{{ product.title }}</a></strong></h5>
                                <p>{{ product.description }}</p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}


                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <h4><a href="#">Місце для чату</a></h4>
                        <p>Сюди можемо згодом додати чат. Бла бла бла. Продавець завжди правий :)</p>
                        <a class="btn btn-primary" target="_blank" href="">Запитай нас</a>
                    </div>

                </div>

            </div>

        </div>
        {% endblock content %}
    </div>
    <!-- /.container -->

    <div class="container">

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Наш Вебсайт 2018</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src='{% static "js/jquery.js" %}'></script>﻿

    <!-- Bootstrap Core JavaScript -->
    <script src='{% static "js/bootstrap.js" %}'></script>

</body>

</html>

shop/templates/category.html
{% extends 'base.html' %}

{% block content %}

{% endblock content %}

shop/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  {{ product.name }}
{% endblock %}

{% block content %}
  <div class="product-detail">
    <div class="col-sm-4">
      <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no-image.jpg"%}{% endif %}" class="img-responsive">
    </div>
    <div class="col-sm-8">
      <h1>{{ product.name }}</h1>
      <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
      <p class="price">
        {{ product.price }} грн.
      </p>
      <form action="{% url "cart:CartAdd" product.id %}" method="post">
        {{ cart_product_form }}
    	{% csrf_token %}
    	<input type="submit" value="Додати в кошик">
	  </form>
      <span>
        {{ product.description | linebreaks}}
      </span>
    </div>
  </div>
{% endblock content %}